# Generated by Django 3.1.7 on 2021-03-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_on_date', models.DateTimeField()),
                ('owner', models.CharField(max_length=100)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
    ]
